"""empty message

Revision ID: 08da7f1e663c
Revises: 32d18cf9d26e
Create Date: 2016-03-08 10:40:29.536000

"""

# revision identifiers, used by Alembic.
revision = '08da7f1e663c'
down_revision = '32d18cf9d26e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('race_hash', sa.String(length=255), nullable=True))
    op.add_column('trace', sa.Column('runner_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'runner_name')
    op.drop_column('race', 'race_hash')
    ### end Alembic commands ###
