"""empty message

Revision ID: 32d18cf9d26e
Revises: 61ce3cd8bf5d
Create Date: 2016-03-07 16:42:29.798000

"""

# revision identifiers, used by Alembic.
revision = '32d18cf9d26e'
down_revision = '61ce3cd8bf5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('group', sa.Integer(), nullable=False))
    op.add_column('race', sa.Column('map', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'race', 'group', ['group'], ['id'])
    op.create_foreign_key(None, 'race', 'map', ['map'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column('race', 'map')
    op.drop_column('race', 'group')
    ### end Alembic commands ###
